name: David Harris
description: words about things I work on
meta_description: "David Harris"
author_description:

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: 'http://davidharris.io'
domain_name: 'http://davidharris.io'
google_analytics: 'UA-105714208-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://davidharris.io'
author:         'David Harris'
